### ISSUE TITLE
Option for 'From' query using css selector instead 'contain text'-only.

### ISSUE THREAD

**Issue by raabbajam** [lukluk/WSQL#1]
tag: _feature request_
**Problem**: Can't target desired element because .from text element is not unique.
**Goal**: to make a better specified selector for parent element in which desired element located. Since 'text'-based only sometimes not enough, due to lack of uniqueness.
Actually, I have not given this too much thougth, so I am not sure if using css selector could solve this problem. But still, a better, wider query option is a plus, isn't it?

```
WSQL v.Alpha
WSQL> open https://www.youtube.com/playlist?list=PL981BABEC1803C00D
WSQL> web.select(LINK).from('DotaCinema').fetch().output
[]
WSQL> web.select('.pl-video-title-link').from('Dota 2 Top Plays Weekly').fetch().output
[]
WSQL> web.select('.pl-video-title-link').from('Dota 2 Top Plays Weekly').fetch().output
[]
WSQL> web.select('.pl-video-title-link').from('Dota 2 Top Plays Weekly').fetch('href').output
[]
WSQL> web.select('.pl-video-title-link').from('Dota 2 Top 10 Weekly - Ep.2').fetch('href').output
[]
WSQL> web.select('.pl-video-title-link').from('DotaCinema').fetch('href').output
[ '/watch?v=FTX943yvuHs&index=85&list=PL981BABEC1803C00D' ]
WSQL> 

```

**Comment by lukluk** [comment]
good idea ok let me fix tha tnow

**Comment by lukluk** [comment]
@raabbajam i will create own branch for this issue

**Comment by lukluk** [comment]
coba di test lagi
https://www.youtube.com/watch?v=0R1IEXYszJM&feature=youtu.be

**Comment by lukluk** [comment]
@raabbajam  saya udah merge ke master update nya
